import type {
  AiProvider,
  InterimSummary,
  SessionIntent,
  StructuredNote,
  TherapeuticOverview,
} from "./types";

// Deterministic, offline provider used when GEMINI_API_KEY is not configured.
// Lets the full AI workflow run in development/demo without external calls.
// Clearly marks its output as generated by a stub.

const STUB_BANNER = "_[נוצר במצב הדגמה ללא חיבור ל‑Gemini]_";

export class StubProvider implements AiProvider {
  readonly name = "stub";

  async transcribeAudio(audio: Buffer, mimeType: string): Promise<string> {
    return `תמליל הדגמה (${mimeType}, ${audio.length} bytes). המטופל/ת דיווח/ה על שיפור במצב הרוח ועל התמודדות טובה יותר עם מצבי לחץ במהלך השבוע.`;
  }

  async summarizeToNote(transcript: string): Promise<StructuredNote> {
    const snippet = transcript.trim().slice(0, 280);
    return {
      content: `**נושאים מרכזיים**
- מצב רוח והתמודדות עם לחץ

**מהלך המפגש**
${snippet || "—"}

**תצפיות קליניות**
- שיתוף פעולה תקין; ללא סימני מצוקה חריפה.

**משימות והמשך**
- המשך מעקב במפגש הבא.

${STUB_BANNER}`,
    };
  }

  async interimSummary(noteText: string): Promise<InterimSummary> {
    return {
      keyTopics: ["מצב רוח", "התמודדות עם לחץ"],
      emotionalState: "יציב, עם נטייה לשיפור",
      progressIndicators: "דיווח עצמי על שיפור בשבוע האחרון",
      observations:
        (noteText.trim().slice(0, 120) || "אין תוכן") + ` ${STUB_BANNER}`,
    };
  }

  async therapeuticOverview(
    sessions: { date: string; content: string }[],
  ): Promise<TherapeuticOverview> {
    return {
      patterns: `נצפו דפוסים עקביים על פני ${sessions.length} מפגשים סביב התמודדות עם לחץ. ${STUB_BANNER}`,
      recurringThemes: ["לחץ", "מערכות יחסים", "ויסות רגשי"],
      progressTrends: "מגמת שיפור הדרגתית במצב הרוח ובאסטרטגיות ההתמודדות.",
      unresolvedIssues: ["דפוסי שינה", "גבולות בעבודה"],
      recommendations: [
        "המשך עבודה על טכניקות ויסות",
        "בחינת דפוסי שינה במפגש הבא",
      ],
    };
  }

  async extractSessionIntent(transcript: string): Promise<SessionIntent> {
    // Naive heuristics so the confirmation flow is demonstrable offline.
    const dateMatch = transcript.match(
      /(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})/,
    );
    let date: string | null = null;
    if (dateMatch) {
      const [, d, m, y] = dateMatch;
      const year = y.length === 2 ? `20${y}` : y;
      date = `${year}-${m.padStart(2, "0")}-${d.padStart(2, "0")}`;
    }
    // Take the first 1-3 word run that looks like a name (very rough).
    const nameMatch = transcript.match(/[֐-׿A-Za-z]+(?:\s+[֐-׿A-Za-z]+){0,2}/);
    return { patientName: nameMatch ? nameMatch[0] : null, date };
  }
}
